---
context: cluster.ada.support
include:
  - name: manifests
    values:
      env: production
      replicas: 3

      # Flag to enable Linkerd to add configuration snippets on ingress
      linkerd: "true"
